//const char* infura = \
//"-----BEGIN CERTIFICATE-----\n" \
//"MIID7zCCAtegAwIBAgIBADANBgkqhkiG9w0BAQsFADCBmDELMAkGA1UEBhMCVVMx\n" \
//"EDAOBgNVBAgTB0FyaXpvbmExEzARBgNVBAcTClNjb3R0c2RhbGUxJTAjBgNVBAoT\n" \
//"HFN0YXJmaWVsZCBUZWNobm9sb2dpZXMsIEluYy4xOzA5BgNVBAMTMlN0YXJmaWVs\n" \
//"ZCBTZXJ2aWNlcyBSb290IENlcnRpZmljYXRlIEF1dGhvcml0eSAtIEcyMB4XDTA5\n" \
//"MDkwMTAwMDAwMFoXDTM3MTIzMTIzNTk1OVowgZgxCzAJBgNVBAYTAlVTMRAwDgYD\n" \
//"VQQIEwdBcml6b25hMRMwEQYDVQQHEwpTY290dHNkYWxlMSUwIwYDVQQKExxTdGFy\n" \
//"ZmllbGQgVGVjaG5vbG9naWVzLCBJbmMuMTswOQYDVQQDEzJTdGFyZmllbGQgU2Vy\n" \
//"dmljZXMgUm9vdCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkgLSBHMjCCASIwDQYJKoZI\n" \
//"hvcNAQEBBQADggEPADCCAQoCggEBANUMOsQq+U7i9b4Zl1+OiFOxHz/Lz58gE20p\n" \
//"OsgPfTz3a3Y4Y9k2YKibXlwAgLIvWX/2h/klQ4bnaRtSmpDhcePYLQ1Ob/bISdm2\n" \
//"8xpWriu2dBTrz/sm4xq6HZYuajtYlIlHVv8loJNwU4PahHQUw2eeBGg6345AWh1K\n" \
//"Ts9DkTvnVtYAcMtS7nt9rjrnvDH5RfbCYM8TWQIrgMw0R9+53pBlbQLPLJGmpufe\n" \
//"hRhJfGZOozptqbXuNC66DQO4M99H67FrjSXZm86B0UVGMpZwh94CDklDhbZsc7tk\n" \
//"6mFBrMnUVN+HL8cisibMn1lUaJ/8viovxFUcdUBgF4UCVTmLfwUCAwEAAaNCMEAw\n" \
//"DwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYEFJxfAN+q\n" \
//"AdcwKziIorhtSpzyEZGDMA0GCSqGSIb3DQEBCwUAA4IBAQBLNqaEd2ndOxmfZyMI\n" \
//"bw5hyf2E3F/YNoHN2BtBLZ9g3ccaaNnRbobhiCPPE95Dz+I0swSdHynVv/heyNXB\n" \
//"ve6SbzJ08pGCL72CQnqtKrcgfU28elUSwhXqvfdqlS5sdJ/PHLTyxQGjhdByPq1z\n" \
//"qwubdQxtRbeOlKyWN7Wg0I8VRw7j6IPdj/3vQQF3zCepYoUz8jcI73HPdwbeyBkd\n" \
//"iEDPfUYd/x7H4c7/I9vG+o1VTqkC50cRRj70/b17KSa7qWFiNyi2LSr2EIZkyXCn\n" \
//"0q23KXB56jzaYyWf/Wi3MOxw+3WKt21gZ7IeyLnp2KhvAotnDU0mV3HaIPzBSlCN\n" \
//"sSi6\n" \
//"-----END CERTIFICATE-----\n" \
//;
// #pragma once
// const char *testnet_ca =
//     "-----BEGIN CERTIFICATE-----\n"
//     "MIIFYzCCBEugAwIBAgIQBFuRvsfto3+Vw79MxWWD4jANBgkqhkiG9w0BAQsFADBG\n"
//     "MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRUwEwYDVQQLEwxTZXJ2ZXIg\n"
//     "Q0EgMUIxDzANBgNVBAMTBkFtYXpvbjAeFw0xODEyMjQwMDAwMDBaFw0yMDAxMjQx\n"
//     "MjAwMDBaMBgxFjAUBgNVBAMMDSouYmluYW5jZS5vcmcwggEiMA0GCSqGSIb3DQEB\n"
//     "AQUAA4IBDwAwggEKAoIBAQCxKuJT2JRRngBdsUC2fYOVmXsID+Jd0hV/GaDppDY6\n"
//     "NqP3oEIoOPzyQj996ct3QlzA/z67zfXWm824t9ridMDEKzYxX5mjew3VC7bRPLD7\n"
//     "bK2Gwe8DykyncoLpdwQWf4a3WOtI/IPHm/fNxqO7nkUiEkrAMjrgQIW6I1XqiPyT\n"
//     "Q3nm+x3CTq/aXcZxDIRqnZqT3drTWRiyr5qIqGO/xORPnC3lNIFMPAMzEzFL9DlN\n"
//     "TrS4RzgvlbeGe7fTR24VhZbf6YgSW7Buo8K77/MYAwcaOf1B861onNiTDO37Opoc\n"
//     "x9hdqIkey/IemWQ8CznEMe/bMakJqgoJFjbypb9iNwLRAgMBAAGjggJ5MIICdTAf\n"
//     "BgNVHSMEGDAWgBRZpGYGUqB7lZI8o5QHJ5Z0W/k90DAdBgNVHQ4EFgQU/st5QvDi\n"
//     "tzSgxjv8SFkNo/zS5vcwGAYDVR0RBBEwD4INKi5iaW5hbmNlLm9yZzAOBgNVHQ8B\n"
//     "Af8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMDsGA1UdHwQ0\n"
//     "MDIwMKAuoCyGKmh0dHA6Ly9jcmwuc2NhMWIuYW1hem9udHJ1c3QuY29tL3NjYTFi\n"
//     "LmNybDAgBgNVHSAEGTAXMAsGCWCGSAGG/WwBAjAIBgZngQwBAgEwdQYIKwYBBQUH\n"
//     "AQEEaTBnMC0GCCsGAQUFBzABhiFodHRwOi8vb2NzcC5zY2ExYi5hbWF6b250cnVz\n"
//     "dC5jb20wNgYIKwYBBQUHMAKGKmh0dHA6Ly9jcnQuc2NhMWIuYW1hem9udHJ1c3Qu\n"
//     "Y29tL3NjYTFiLmNydDAMBgNVHRMBAf8EAjAAMIIBBAYKKwYBBAHWeQIEAgSB9QSB\n"
//     "8gDwAHYAu9nfvB+KcbWTlCOXqpJ7RzhXlQqrUugakJZkNo4e0YUAAAFn4C+qqwAA\n"
//     "BAMARzBFAiEAwTv4xb5O15uD8HueEd0G1qifGqFEFC3PBM9HUdQNVeYCIFR2SvIH\n"
//     "SZiDoN7Ekt4I1eTZqTvCEfAWnlNm0yOHhhrZAHYAh3W/51l8+IxDmV+9827/Vo1H\n"
//     "Vjb/SrVgwbTq/16ggw8AAAFn4C+rhQAABAMARzBFAiBvseRQHAi4aKfl971EvGhr\n"
//     "eO3G/05dzhug1juw3kzN4QIhAJ3ZJHlRzv+sR7a4Xxkj2M8OkEuUm+mFeAFD7lKt\n"
//     "AzQCMA0GCSqGSIb3DQEBCwUAA4IBAQBUAoOxg+9cmp++A46JXIoBSrHvDcfkaebh\n"
//     "Ryk026Lud5NyWj1150PThhJzN3X0pnyuz22mUItsJEt7VszR3GgpYKq0s7TFKL/w\n"
//     "HfO9jgiNaRtogDTpnzCsJQVl8LEYJpxOZObTBxldma+JOLT3ixqvX+bQokwyVxVj\n"
//     "rygRsvON4Z5+WvDOURV/xQZgevJMU656meJ2aeDjdHEQbLSxQXUmGiJypf5xWnUj\n"
//     "EBXTGW7saash0rg2uF3d7ry4zoXEbTINaEY71X3v7uM78Vrae3MXL139+iEp2Nqx\n"
//     "YyOb3JIiuK0JBpAR//mrlkbXQytT2aQzlGAj6TdrCZ6Q0j7BboAm\n"
//     "-----END CERTIFICATE-----\n";
